version: "3.9"

services:
  mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - banking-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      databaseurl: ${MONGO_URL}
      tokenkey: ${TOKEN_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - mongodb
    networks:
      - banking-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - banking-net

volumes:
  mongo_data:

networks:
  banking-net:
    driver: bridge
